#!/usr/bin/env bash
set -eo pipefail

#export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=demo,app.kubernetes.io/instance=demo" -o jsonpath="{.items[0].metadata.name}")
#echo "Visit http://127.0.0.1:8080 to use your application"
##kubectl --namespace default port-forward $POD_NAME 8080:80
#kubectl --namespace default port-forward $POD_NAME 8080:8080


minikube service demo-demo
