apiVersion: apps/v1
kind: Deployment
metadata:
  name: statelessapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: statelessapp
  template:
    metadata:
      labels:
        name: statelessapp
    spec:
      containers:
        - name: statelessapp-container
          image: "kubedemo/statelessapp"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
