apiVersion: v1
kind: Service
metadata:
  name: statelessapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: statelessapp

---

apiVersion: v1
kind: Service
metadata:
  name: statefulapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: statefulapp
