apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-demo
  labels:
    helm.sh/chart: demo-0.1.0
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-statefulapp
  labels:
    helm.sh/chart: demo-0.1.0
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
