apiVersion: v1
kind: Service
metadata:
  name: statefulapp
  labels:
    name: statefulapp
spec:
  ports:
    - port: 8080
      name: http
  clusterIP: None
  selector:
    name: statefulapp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulapp
  labels:
    name: statefulapp
spec:
  replicas: 1
  serviceName: statefulapp
  selector:
    matchLabels:
      name: statefulapp
  template:
    metadata:
      labels:
        name: statefulapp
    spec:
      containers:
        - name: statefulapp
          image: "kubedemo/statefulapp"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: statefulapp-storage
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
  volumeClaimTemplates:
    - metadata:
        name: statefulapp-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
