#!/usr/bin/env bash
set -eo pipefail

for i in {1..10000}
do
   curl -s -w "\n" $1/api >> OP &
   if ! (($i % 100)); then
      wait;
   fi;
   if ! (($i % 1000)); then
      echo $i;
   fi;
done;
cat OP | jq '.hostname' | sort | uniq -c | sort -rn
