#!/usr/bin/env bash
set -eo pipefail

# Get some summary stats on subreddits. 
# cat subreddits.json|jq '.audience_target' | sort | uniq -c | sort -rn > audience_targets

# Choose some audience_targets, and now create a new, more targeted json database
cat subreddits.json | jq -c '
   select(.audience_target != null) | 
   select(.audience_target | in(
      {"technology":1,"gaming":1,"programming":1,"pets":1,"outdoors":1,"scifi":1,"beerspirits":1,"cycling":1,"food_drink":1,"running":1}
   )) | 
   {"audience": .audience_target, "name": .display_name_prefixed, "description": .public_description}' |\
   tee >(jq '.' --slurp > targeted.json) | jq '.'
